### ISSUE TITLE
Send notification when mentioning user

### ISSUE THREAD

**Issue by Marahin** [Marahin/letter-bot#11]
![obraz](https://github.com/Marahin/letter-bot/assets/2716041/8bf4ba1f-7a52-411c-81cb-6f0906124ccf)

**Comment by BlackMadamnn** [comment]
Imo na pw byłoby najlepiej, i nie ważne kto kogo z jakiej gildii. Napisanie do kogoś „cześć, overbookowalem Cię na asurach” nie trwa 5 min, a ktoś przynajmniej wie jasno i wyraźnie że mu spot przepadł  a jak ktoś potrzebuje 30 min overbookowac kogoś z 3h to już wgl bajka żeby się dogadać
