### ISSUE TITLE
Reduced reservations don't seem to apply when there's non-multilevel zone 

### ISSUE THREAD

**Issue by Marahin** [Marahin/letter-bot#3]
R1 Bashmuu 21 : 01 - 22 : 44
R2 Prison -1 16 : 00-17 : 00
R3 Prison -2 16 : 00-17 : 00

**Comment by Marahin** [comment]
![obraz](https://github.com/Marahin/letter-bot/assets/2716041/bafd123d-7b64-4df8-8fb1-ddb9be88db41)
Ordering matches

**Comment by Marahin** [comment]
![obraz](https://github.com/Marahin/letter-bot/assets/2716041/6ba812fd-b47c-4fa1-a48b-52942fc4339f)
🤔  @patryk-fuhrman

**Comment by patryk-fuhrman** [comment]
The issue was that we didn't break the reduce loop when we have found the reservation with the same start and end time. Order was indeed important.
